[package]
name = "gantry-substreams"
version = "0.1.0"
edition = "2021"

[lib]
name = "gantry_substreams"
crate-type = ["cdylib"]

[dependencies]
substreams = "0.6"
substreams-ethereum = "0.10"
prost = "0.13"
prost-types = "0.13"
hex = "0.4"
substreams-entity-change = "2"

[profile.release]
lto = true
opt-level = "s"
strip = "debuginfo"
