// @generated
// This file is @generated by prost-build.
/// Swaps as emitted by a Uniswap v4 PoolManager, in block order.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swaps {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<Swap>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(uint32, tag="2")]
    pub log_index: u32,
    #[prost(string, tag="3")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub sender: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub zero_for_one: bool,
    #[prost(string, tag="6")]
    pub amount_in: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub amount_out: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub tx_from: ::prost::alloc::string::String,
}
/// One address opening and closing a position around somebody else's trade.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sandwiches {
    #[prost(message, repeated, tag="1")]
    pub sandwiches: ::prost::alloc::vec::Vec<Sandwich>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sandwich {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub pool_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub attacker: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub victims: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag="5")]
    pub frontrun_index: u32,
    #[prost(uint32, tag="6")]
    pub backrun_index: u32,
    #[prost(string, tag="7")]
    pub attacker_eoa: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
